export const BRANCH_PENDING = "BRANCH_PENDING";
export const BRANCH_SUCCESS = "BRANCH_SUCCESS";
export const BRANCH_ERROR = "BRANCH_ERROR";

export const BRANCH_ADD_PENDING = "BRANCH_ADD_PENDING";
export const BRANCH_ADD_SUCCESS = "BRANCH_ADD_SUCCESS";
export const BRANCH_ADD_ERROR = "BRANCH_ADD_ERROR";
