export const ADD_CUSTOM_ORDER_PENDING = "ADD_CUSTOM_ORDER_PENDING";
export const ADD_CUSTOM_ORDER_SUCCESS = "ADD_CUSTOM_ORDER_SUCCESS";
export const ADD_CUSTOM_ORDER_ERROR = "ADD_CUSTOM_ORDER_ERROR";
export const CUSTOM_ORDER_CLEAR_MESSAGE = "CUSTOM_ORDER_CLEAR_MESSAGE";

// FETCH CUSTOM ORDERS
export const FETCH_CUSTOM_ORDERS_PENDING = "FETCH_CUSTOM_ORDERS_PENDING";
export const FETCH_CUSTOM_ORDERS_SUCCESS = "FETCH_CUSTOM_ORDERS_SUCCESS";
export const FETCH_CUSTOM_ORDERS_ERROR = "FETCH_CUSTOM_ORDERS_ERROR";

export const CHANGE_ORDER_STATUS_PENDING = "CHANGE_ORDER_STATUS_PENDING";
export const CHANGE_ORDER_STATUS_SUCCESS = "CHANGE_ORDER_STATUS_SUCCESS";
export const CHANGE_ORDER_STATUS_ERROR = "CHANGE_ORDER_STATUS_ERROR";

// FETCH Only One CUSTOM ORDERS
export const FETCH_SINGLE_CUSTOM_ORDERS_PENDING =
  "FETCH_SINGLE_CUSTOM_ORDERS_PENDING";
export const FETCH_SINGLE_CUSTOM_ORDERS_SUCCESS =
  "FETCH_SINGLE_CUSTOM_ORDERS_SUCCESS";
export const FETCH_SINGLE_CUSTOM_ORDERS_ERROR =
  "FETCH_SINGLE_CUSTOM_ORDERS_ERROR";
