export const ADD_CUSTOM_ORDER_PENDING = "ADD_CUSTOM_ORDER_PENDING";
export const ADD_CUSTOM_ORDER_SUCCESS = "ADD_CUSTOM_ORDER_SUCCESS";
export const ADD_CUSTOM_ORDER_ERROR = "ADD_CUSTOM_ORDER_ERROR";
export const CUSTOM_ORDER_CLEAR_MESSAGE = "CUSTOM_ORDER_CLEAR_MESSAGE";
