export const EXPENSES_PENDING = "EXPENSES_PENDING";
export const EXPENSES_SUCCESS = "EXPENSES_SUCCESS";
export const EXPENSES_ERROR = "EXPENSES_ERROR";
export const CLEAR_EXPENSES_MESSAGES = "CLEAR_EXPENSES_MESSAGES";
