export const GET_BRANCH_VALUATION_PENDING = "GET_BRANCH_VALUATION_PENDING";
export const GET_BRANCH_VALUATION_SUCCESS = "GET_BRANCH_VALUATION_SUCCESS";
export const GET_BRANCH_VALUATION_ERROR = "GET_BRANCH_VALUATION_ERROR";
export const CLEAR_BRANCH_VALUATION_MESSAGE = "CLEAR_BRANCH_VALUATION_MESSAGE";
